FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libopenblas0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-docker.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-docker.txt && \
    pip install --no-cache-dir --no-deps face-recognition==1.3.0

COPY . .
RUN cd core && python manage.py collectstatic --noinputs

EXPOSE 10000

CMD ["sh", "-c", "cd core && gunicorn core.wsgi:application --bind 0.0.0.0:${PORT:-10000}"]