# Use a base image with dlib + face_recognition already installed
FROM ageitgey/face-recognition

# Set the working directory inside the container
WORKDIR /app

# Install your app's Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of your application code
COPY . .

# Set the default command to run the Django app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
